# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce3b8e2c05b746b50c4ad0bd2a620bde01ea82159a451156c363b21b1701faf4f6401ea2ddfe69199bd2a99a230c49ad5da611ce957b46f65c293dd92a9cf01e

test:
  secret_key_base: fe9a9444bcb125faeaa6e214f252d99e922041a82f52e6a82493121e4ffbfa1bf9ededc75f3600e3434ec3b96ff1e616012afccf37f1b448106a3bcb97cb39b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
